version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: task-db
    restart: always
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: task-api
    ports:
      - "3000:3000"
    networks:
      - task-network
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: task-web
    ports:
      - "8080:80"
    networks:
      - task-network
    depends_on:
      - api

networks:
  task-network:
    driver: bridge
